<?php
/**
 * Ska Smart Virtual Template
 * This file is automatically generated. Do not edit directly.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

global $ska_current_template_id;
$wrapper = \Ska_No_Code_Design\Theme_Builder\Ska_Virtual_Wrapper::get_instance();

?><!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
	<meta charset="<?php bloginfo( 'charset' ); ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?php wp_head(); ?>
</head>
<body <?php body_class( 'ska-builder ska-virtual-app' ); ?> x-data>

<?php wp_body_open(); ?>

	<?php
	// 1. Render Global Header
	$wrapper->render_location( 'header' );
	?>

	<main id="primary" class="ska-main-content">
		<?php 
		// 2. Render Main Route Content (Single, Archive, 404)
		if ( ! empty( $ska_current_template_id ) ) {
			$wrapper->render_template_by_id( $ska_current_template_id );
		} else {
			// Fallback: Render default content if no main template is defined
			echo '<div class="ska-container mx-auto p-4">';
			if ( have_posts() ) {
				while ( have_posts() ) {
					the_post();
					the_content();
				}
			}
			echo '</div>';
		}
		?>
	</main>

	<?php
	// 3. Render Global Footer
	$wrapper->render_location( 'footer' );
	?>

<?php wp_footer(); ?>

</body>
</html>